nodejs:
  applicationPort: 3100
  aadIdentityName: pt
  ingressHost: pt-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctsprod.azurecr.io/pt/frontend:latest'
  keyVaults:
    pt:
      secrets:
        - redis-connection-string
        - app-insights-connection-string
  environment:
    REDIS_TTL: 6000
    REDIS_SESSION_PREFIX: 'pcs'

redis:
  enabled: false
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false
