nodejs:
  applicationPort: 3100
  aadIdentityName: rpt
  ingressHost: rpt-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctsprod.azurecr.io/rpt/frontend:latest'
  #  Uncomment once the vault containing the app insights key has been set up
  #  keyVaults:
  #    rpt:
  #      secrets:
  #        - AppInsightsInstrumentationKey
  environment:
